language: node_js
node_js:
- stable
cache: npm
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: O549XVsVtfWNGOGSQocLfcI9Idw4CxAuWlRxKxZESq9ClygO54/Ju3MGqtQPPXGZHq0piDXjG0XxVZnbqUNQpdI96dbe2G+msneVvz70SdTuuODOEd5vHfK6rIPMPVVCQ6ePp2CmzhA/kwGgyuYraNIYfqMLRY1vFqDmU2QCIVu/+rA+4kOmNZH2JEj2pWMlOsMkPj2fuLW8icGv+v3/9S0MQwvMKIKMVssCh9daNDH+2uI7gLzauszSd1Tw1qBPKC9uJaJMmaIydMFWn70flPLnx7M2GbXlGtwhn4neiEn91ujdnzyf+URXGbpyKdPqKSlWQruIZ+DR3ArDji7yjWWb0lMyLwoeA8hAy8OCnRAEPUgqkzWmpfEXN8rKwbhDfDPqDqkBanW3s0lBGuC1TfMIKH7O2FUxqQy2PvAbEmreOc57ENzZO5SYtHaMG0FswFraZU7qsEaI9/e7+jvDKNpuVGe0qOHjp8kp9AgIgRXBuUqxT1eu9F1SMyGuvLc7imrj4GowdoEyaF6M0bnpiviLk3eC8XDPvatuSDqiseCDf1fBFsXD2qwE9Qc1gvt5HajrPPMXRaleFePysG02PB43Jq0th8YWJjesIdPxEvd1CU3abGkUSViv1M5oR0jP+dIuNdZcswKlvN/lWC3X8yYMV3XMk0BnDcAifmOt1l0=
