language: node_js
node_js:
- stable
cache: npm
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: jZl2mel8mWiuDGyAd/BjN7BvY9CwwVeSCgsGgSpEC9xoIleJMyrxtqcBd2KueEAaaG3EY4Ic0i3vVfXClyaAvUsgvsing4ZBmL2nMPpJJVrF5PnUyaoqrmDpp+tDEQhnsC5gt5tKdYUA84rI/gespCmGPRNvVClmkvUoPSdtNVH1GFyfT4k7G2S747vIAAXXxsCb1lH37zP1VCRpurfYYG0wrBopvyzF0ZoB2Wcq9zmyKRaAOXJrbdLlXkhLSbenL7P788gd//Fz6+bjf7PXFy1P7SnHCkUrRydP2NGblRuPz5AlLlomxyDxEeX6uGtEEpxZh4mF3LSPgpb66zAGnWvHU2LWR9qCMRDL8t2JBJlNBbAyea7BRZfatDJPzPj0Q4JQim+6zxL6qB4U7/2HRLSwWJBDabuxoVlZZm4oUHU2sIvKPwCc9W12GNqJNbraV0qqgToCHT8PK3zPyPTUg47HlMDlaKPZ/bHxR8BdkJjPIlOjCZegCd25E71ZkMhl2iATCc59X9IWelqPHagZ7Jb/B1H+351zG4WsmfmImn1YdDf8f7whc/0xClk54lk3IoPzXohNR97CrEQ5ZRgi+G1kHEAPGIpzGKY4dYYDInVL7Nb79ho6V3u3A1xAQRq09ULWQx3JbymRoANgUPl08dsZz4GrNqqBT9fzy4br/kU=
