version: '3'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - app-network
  api:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - PORT=8080
    links:
      - sonarqube
networks:
  app-network:
    driver: bridge